# secrets.toml

GEMINI_API_KEY = "AIzaSyCK91Rgb-TiLviLoqY8Okgb2roRAIH_Dws"
SPREADSHEET_ID = "1HUvt5pRS_dC6n-3zGqPm4pyz2lygHxKESYG0ljzhUfU"

[gcp_service_account]
type = "service_account"
project_id = "grao-lar-assistente"
private_key_id = "b2aa602c86899b0bb787303f1f04617e48f94d93"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDjL5bBbaR7s/oY
I2wDUr18WgjR3S9o4AoMR5/HuJT41IEHRXvCN/fOcx8ASWzjX1eSzGiD1LhQZ3yo
x3soHx/QKwFNtSPeGPB8HvyhprvrDEvlB9S2x0GZ876fJ0EuB8hRBpkRL2PJxCH0
fgdimA0kmu0mBD3T3eZeVm2//+Ge++tQnUqv+1YJTiAZxkQV4MBGIXX/8kr0YikT
7vcPf6/ZmElxI9xW5QSwLvMSSL6nFw497DWQpgPz98CjKzPPJz7ISQjT2sbPEAbj
eOQy+qxOxijxp+Y53CM4tDwhNCjjAMA8Ad2kjJEdDB1ohugAvKCUuhIEekFbJPsh
rnpbYiYvAgMBAAECggEAMzg99WMaU9dqWbnWttMXLGuCFIqZDzx/l3AoeldHougK
JREJy2ph4LY8tYxYU9ThghO6tooled8zEDxVLGEEA6NGenYN3Zti0KEN1QYp1N7j
V4IR95lp1WNKRUiM3etcQsRJi0HTbiBdhWlKkfR09h1FvS30oIklUHyM5t4ySGzX
pXvkPxnhhU7ULL+NkpjknUXiIPM42/PEG0zRLA9HpUDv+noT5/6FyUegBcqRloke
tXNl+gRvU03PGgR7gitqGBxMBdouoydFPEFStAl946EyL3MtpJWuILW+V/UQon1d
WoZUBFlyhu2sh2pr0bxZ4Y1SEMJ7rl/gevCL/POmeQKBgQD+Wq147HxIUmnoaFFn
vgvJmouIejMk6DVEeQGCD3Kmy5gPwiKSIZJq268wxcgwJB50LcWsdx0jfEepcqjA
mq0gqXt78MY/QEFaIMJHpfEpKF9LXUE6otl5mAMGH02pWE+gUuIhC2xQG260tjkF
iK/GMuwPL+ZhJib3SPRdMovCxwKBgQDkp+iZYFrXFRP+hlhy/6A8p9oZPSCehU7K
TZ7QnQrdtpKS57zscFhHae/p2Mn+tETBAIMQ8g8YYgud4EER6r9mUTb6AxqM7E7+
M29k0NAhQ8kDAotvNEx3tG3Cj5o8f3ksUWWwi3t+oxBDfMbIADQV8RiCvyc5wj/8
eAn2QQoZWQKBgFtrNfxHaygHTv90NwYFfXEZdds4qJc0SqjwoQUhDkE63c2UJh7F
qD119hKek6QR50w0g17IdRWi/pK9nj+TmHQr1jEmyepD6vk82vcrgnEbjJymyOIN
VALrCvMxXxVlo0DpaVMdKvHj2jdjYz1E8oBXHxcaTUBPmSO5+fJhT3BTAoGBAKBt
Ai/iP7nZ6w5P+eytVyJXbhj5H1K5Gx+rN/sLw9zsxIfXmWCWLgnk1NPQK2DN39M9
5bdU7axg1d+twFmuxx0lbBobZVxsS7vkIIquSuib44N+HJAoNGJkMAIquL8rfLvQ
XDVyl3GxPK7s85bNNb4TSuwo63+Fv1kGa47f8RL5AoGAVP/9bdlnEUtWNMFMmcCP
DJJgBm/ts/qrauA/raVgOz6/Vfh5qsti4WUfpvOGH7G1WREvDShG7hR+gOxAe6Qm
tB+lLKpgWK0i8ZKA3Ao3smhD7T+4riKwDlbXMotAOctvCZjF3D6gEBhj0CHg8HVA
IBHlyQyMPiuA/Ucs1sSgIGs=
-----END PRIVATE KEY-----"""
client_email = "grao-lar-assistente@grao-lar-assistente.iam.gserviceaccount.com"
client_id = "117995493979280044074"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/grao-lar-assistente%40grao-lar-assistente.iam.gserviceaccount.com"
universe_domain = "googleapis.com"



